@echo off
echo Running AIResumeScreener...
java -cp "target/classes;lib/gson-2.10.1.jar;lib/pdfbox-app-3.0.5.jar;lib/poi-5.2.3.jar;lib/poi-ooxml-5.2.3.jar;lib/poi-ooxml-full-5.2.3.jar;lib/commons-compress-1.21.jar" com.resumescreener.Main